### ISSUE TITLE
Not working with Armenian characters

### ISSUE THREAD

**Issue by Elawphant** [modxcms/Tagger#108] opened 2017-06-15 06:07 UTC
When putting an Armenian word or expression in the field for new tags, it takes only one part of it, e.g. I put Real estate (Անշարժ գույք) it takes only Rea (Անշ). also, impossible to edit alias, first tag is assigned alias -1, and refusing to change to Armenian text.
Second and consecutive tags alias are empty with same behavior: impossible to change to Armenian alias.

**Comment by Moonbase59** [comment] 2017-06-20 16:43
Maybe the cause is the same as mine, see https://github.com/modxcms/Tagger/issues/109

**Comment by theboxer** [comment] 2017-06-27 15:39
Should be fixed with #109

**Closed by theboxer** 2017-06-27 15:39 UTC
