### ISSUE TITLE
Resources losing tags upon edit

### ISSUE THREAD

**Issue by davidpede** [modxcms/Tagger#80] opened 2015-08-06 10:10 UTC
I am having an issue with Tagger.

Have around 100 resouces within a Collections container which all have access to tags split between 8 groups like so:

![tags](https://cloud.githubusercontent.com/assets/825106/9109098/01f03a4e-3c2b-11e5-8af4-630fd3924b5f.jpg)

Everything is working really well until I go back to a resource and edit it. I could change something like the menutitle or a TV value, save the resource and Tagger will lose some of its tags but not all. This dosn't happen everytime and its not always the same tags or groups. There seems to be no pattern to it and there's nothing in the error log.

Not sure where to even start looking for the problem but its causing massive problems across a large site that relys on the tagging system.

Any help or advice asap would be really appreciated!

I'm using Tagger 1.7.0-pl & MODX 2.3.5-pl (advanced).

**Comment by theboxer** [comment] 2015-08-06 15:17
Hello, this is already solved issue and will be fixed in next release. If you need it before the release will be live, you can grab those changes: 4186ea3d6d8f18a33fd5480db0beca5fa4723da6

**Closed by theboxer** 2015-08-06 15:17 UTC

**Comment by davidpede** [comment] 2015-08-06 15:39
Works perfectly now, thanks for the quick response! Great extra!

**Comment by davidpede** [comment] 2017-07-02 11:26
Hi @theboxer

Know this quite old but have had this problem again. Happens when the 'Group > Place' is set to 'In TV's Section'.

All tags in groups set to 'In TV's Section' are lost when I change something like the menutitle or a TV value.

Works fine when set to 'In Tab'.

Shall I open a new issue...?

**Comment by theboxer** [comment] 2017-07-03 07:53
Can't reproduce, tags are still there...

**Comment by davidpede** [comment] 2017-07-03 08:41
Been looking at this more and the probem only occures on resources using simpleCart. Standard modx resource types work as expected.

**Comment by theboxer** [comment] 2017-07-04 08:00
Than you'll have to ask at simpleCart :)
